package eu.europeana.metis.common.rdf;

import java.io.StringReader;
import java.io.StringWriter;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Deque;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLEventFactory;
import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLEventWriter;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.events.Attribute;
import javax.xml.stream.events.Characters;
import javax.xml.stream.events.StartElement;
import javax.xml.stream.events.XMLEvent;

/**
 * <p>This class implements hierarchy normalization on the element hierarchy in RDF+XML content. The
 * problem this functionality aims to solve is that RDF resources (represented by XML elements) can
 * have any kind of nesting, even when generated by Jena (e.g., exported from a model). This
 * functionality solves the issue by 'flattening' the hierarchy in such a way that all resource
 * elements (those with a <code>rdf:about</code> value) are moved to the top of the hierarchy (i.e.,
 * directly underneath the root element, which is assumed to be <code>rdf:RDF</code>). Resource
 * references (<code>rdf:resource</code> attributes) are inserted in the former parent element.
 * Blank nodes (nested anonymous elements without a <code>rdf:about</code> value) will be left
 * untouched. The result will be made "pretty": indented with an indent of 2 spaces.
 * </p>
 * <p>For example, consider the following XML (omitting the namespace declarations):</p>
 * {@snippet lang = "XML":
 * <rdf:RDF>
 *   <Book rdf:about="book_1">
 *     <title>A tale of two cities</title>
 *     <hasAuthor>
 *       <Author rdf:about="author_A">
 *         <name>Charles Dickens</name>
 *       </Author>
 *     </hasAuthor>
 *   </Book>
 * </rdf:RDF>
 *}
 * <p>Hierarchy normalization will transform this data into the following equivalent structure:</p>
 * {@snippet lang = "XML":
 * <rdf:RDF>
 *   <Book rdf:about="book_1">
 *     <title>A tale of two cities</title>
 *     <hasAuthor rdf:resource="author_A"></hasAuthor>
 *   </Book>
 *   <Author rdf:about="author_A">
 *     <name>Charles Dickens</name>
 *   </Author>
 * </rdf:RDF>
 *}
 * <p>The benefit of hierarchy normalization lies in normalizing the otherwise unpredictable
 * structure of XML data. This is useful, for instance, ahead of applying an XSLT: the XSLT can now
 * be made to assume the flattened structure and hence be simpler.
 * </p>
 * <p> This implementation of hierarchy normalization is not streamed, as we need to keep
 * significant portions of the content in memory (namely, all nested elements, so that we can add
 * them in later at the right place). This means that this implementation is designed to work with
 * small amounts of data (like individual records and contextual items). A logical alternative would
 * have been to load in Jena and then write some custom export tool. This seems to be more complex
 * than the approach implemented here (even though it could perhaps have been made more performant).
 * </p>
 * <p> <b>Please note:</b> <i>The input data is assumed to be valid RDF+XML.</i> This means that
 * this functionality does not check RDF+XML compliance, but rather acts 'in good faith'. One
 * example: if a property has multiple child resources in the input data (not allowed in RDF+XML),
 * the caller may not be notified. Instead, the property will have a reference to just one of the
 * resources, and the reference to the other one may be lost.
 * </p>
 * <p> <b>Exception to the above:</b> At the time of writing, some provenance information is
 * encoded in a manner that is not compliant with RDF+XML. Specifically, attributes
 * <code>edm:wasGeneratedBy</code> and <code>edm:confidenceLevel</code> are accepted on
 * properties. As this does not affect the structure of the data, hierarchy normalization as
 * implemented here will accept and preserve these annotations.
 * </p>
 */
public final class RdfXmlHierarchyNormalization {

  private static final String RDF_NAMESPACE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
  private static final String RDF_ABOUT = "about";
  private static final String RDF_RESOURCE = "resource";

  /**
   * Perform hierarchy normalization on the provided content.
   *
   * @param content The content to normalize.
   * @return The normalized content.
   * @throws XMLStreamException Unexpected processing errors (typically RDF compliance issues).
   */
  public static String normalizeHierarchy(String content) throws XMLStreamException {

    // Set up the input with the XML data as provided.
    final XMLEventFactory eventFactory = XMLEventFactory.newInstance();
    final XMLEventReader reader = XMLInputFactory.newInstance()
        .createXMLEventReader(new StringReader(content));

    // Create and bootstrap the nested element (scope) stack (that includes the top-level element)
    // and the list of elements (that excludes the top-level element). Note: we will add new
    // nested elements to the list upon creation: this creates a breadth-first list (if we were to
    // add it upon completion, we would get a depth-first list instead).
    final NestedElement topLevelElement = new NestedElement(true);
    final Deque<NestedElement> elementStack = new ArrayDeque<>();
    elementStack.add(topLevelElement);
    final List<NestedElement> allNestedElements = new ArrayList<>();

    // Read all events and separate them by element, preserving the order within each nested element.
    while (reader.hasNext()) {
      final XMLEvent currentEvent = reader.nextEvent();

      // Start writing a new nested element if we find an element with an ID (i.e., rdf:about
      // value). We make an exception for the root element (i.e., rdf:RDF) as we should never
      // create a nested element for it or its children (they are already in the right place).
      // We must also add a new reference to the parent element.
      final boolean isNotAtRootElementBeforeEvent = elementStack.size() > 1 ||
          elementStack.getLast().getCurrentDepth() > 1;
      if (isNotAtRootElementBeforeEvent && currentEvent.isStartElement()) {
        final StartElement element = currentEvent.asStartElement();
        final String elementId = Optional.ofNullable(element.getAttributeByName(
                new QName(RDF_NAMESPACE, RDF_ABOUT)))
            .map(Attribute::getValue).filter(id -> !id.isBlank()).orElse(null);
        if (elementId != null) {
          elementStack.getLast().setReferenceForExtractedNestedElement(elementId, eventFactory);
          final NestedElement nestedElement = new NestedElement(false);
          elementStack.addLast(nestedElement);
          allNestedElements.add(nestedElement);
        }
      }

      // Add the element and maintain the counter.
      elementStack.getLast().addEventAndUpdateDepth(currentEvent);

      // Finalize the nested element if we have just ended its root element. All we need to
      // do is pop it from the stack, then we're back in the parent where we left off, we continue
      // writing there. Of course, we only do this if we are not already in the top-level element.
      if (currentEvent.isEndElement() && elementStack.getLast().getCurrentDepth() == 0
          && elementStack.size() > 1) {
        elementStack.removeLast();
      }
    }

    // Set up the output for the normalized XML data.
    final StringWriter flattenedWriter = new StringWriter();
    final XMLEventWriter writer = XMLOutputFactory.newInstance().createXMLEventWriter(flattenedWriter);
    new PrettyPrintingWriterWrapper(writer, eventFactory).write(topLevelElement, allNestedElements);

    // Done
    return flattenedWriter.toString();
  }

  /**
   * This represents a node of content in the hierarchy. This is either the top level element (i.e.,
   * the document, the <code>rdf:RDF</code> and its immediate children), or it represents a nested
   * element with <code>rdf:about</code> value and its content. This element also purges all
   * spacing/indenting from the content.
   */
  private static class NestedElement {

    // The last event in this list is always a non-character event.
    private final List<XMLEvent> events = new ArrayList<>();

    // Character events are buffered here until they can all be written.
    private final List<Characters> characterBuffer = new ArrayList<>();

    // The current depth at which we are adding.
    private int currentDepth = 0;

    // Indicates whether this is the top-level element in the data.
    private final boolean isTopLevelElement;

    /**
     * Constructor.
     *
     * @param isTopLevelElement Whether this is the top-level element.
     */
    public NestedElement(boolean isTopLevelElement) {
      this.isTopLevelElement = isTopLevelElement;
    }

    /**
     * We are at the root element (i.e., rdf:RDF) if and only if this is the top level element and,
     * within this element, we are not deeper than depth 1 (i.e., inside rdf:RDF but not inside any
     * of its child elements).
     *
     * @return True if and only if we are not at the root element.
     */
    private boolean isNotAtRootElement() {
      return !this.isTopLevelElement || getCurrentDepth() > 1;
    }

    /**
     * Adds an event to this element. This method is used while we are receiving events, and we
     * determine it should be part of this element. We update other properties of this element
     * based on the event that is received.
     *
     * @param event The event to add.
     */
    public void addEventAndUpdateDepth(XMLEvent event) {

      // Add the event. Characters go into the buffer. If we find a non-character event, we
      // decide on whether to add all the characters to the event list, or discard (purge) them.
      // We only add the characters if we are between a start and an end, and the start does not
      // have a rdf:resource link. So between start and start, between end and end, and between
      // end and start, we don't add characters. Also, we always purge at the top level element.
      if (event.isCharacters()) {
        this.characterBuffer.add(event.asCharacters());
      } else {
        final boolean isBetweenNonReferenceStartAndEnd = !events.isEmpty() &&
            events.getLast().isStartElement() && event.isEndElement() &&
            events.getLast().asStartElement().getAttributeByName(
                new QName(RDF_NAMESPACE, RDF_RESOURCE)) == null;
        if (isBetweenNonReferenceStartAndEnd && isNotAtRootElement()) {
          events.addAll(characterBuffer);
        }
        characterBuffer.clear();
        events.add(event);
      }

      // Update the depth. Must be after deciding on purging so that the depth still reflects
      // the depth of the characters for which we are making this decision.
      if (event.isStartElement()) {
        currentDepth++;
      }
      if (event.isEndElement()) {
        currentDepth--;
      }
    }

    /**
     * This method is called as we are receiving events, and we determine that we need to start a
     * new (nested) element. We register the new event (by its <code>rdf:about</code>) with this
     * element, as a <code>rdf:resource</code> reference needs to be added.
     *
     * @param reference    The reference to register.
     * @param eventFactory The event factory for creating the attribute with the reference.
     */
    public void setReferenceForExtractedNestedElement(String reference, XMLEventFactory eventFactory) {

      // The last added non-character element at this point must be a start element. Add the
      // reference only if we are not looking at the content's root element (rdf:RDF) and the
      // element does not already have a reference (which would be against RDF+XML rules).
      final StartElement currentElement = events.getLast().asStartElement();
      final boolean doesNotContainReference = Optional.ofNullable(currentElement.asStartElement()
              .getAttributeByName(new QName(RDF_NAMESPACE, RDF_RESOURCE)))
          .map(Attribute::getValue).filter(value -> !value.isBlank()).isEmpty();
      if (isNotAtRootElement() && doesNotContainReference) {
        final Iterable<Attribute> currentAttributes = () -> Optional
            .ofNullable(currentElement.getAttributes()).orElse(Collections.emptyIterator());
        // TODO be smarter about the prefix: check the namespace declarations in the doc.
        final Attribute newAttribute = eventFactory.createAttribute(
            new QName(RDF_NAMESPACE, RDF_RESOURCE, "rdf"), reference);
        final Iterator<Attribute> newAttributes = Stream.concat(Stream.of(newAttribute),
            StreamSupport.stream(currentAttributes.spliterator(), false)).iterator();
        final StartElement newElement = eventFactory.createStartElement(
            currentElement.getName().getPrefix(), currentElement.getName().getNamespaceURI(),
            currentElement.getName().getLocalPart(), newAttributes, currentElement.getNamespaces(),
            currentElement.getNamespaceContext());
        events.set(events.size() - 1, newElement);
      }
    }

    public int getCurrentDepth() {
      return currentDepth;
    }

    public List<XMLEvent> getEvents() {
      return Collections.unmodifiableList(events);
    }
  }

  /**
   * This is a wrapper around an event writer that adds indentation based on the current depth.
   */
  private static class PrettyPrintingWriterWrapper {

    // The indent size (number of spaces).
    private static final int INDENT_SIZE = 2;

    // The wrapped writer.
    private final XMLEventWriter writer;

    // The factory for creating (indent) events.
    private final XMLEventFactory eventFactory;

    // The current depth while writing.
    private int depthCounter = 0;

    // The last event that was a start or an end: is used to determine whether to indent.
    private XMLEvent lastStartOrEndEvent = null;

    /**
     * Constructor.
     *
     * @param writer       The wrapped writer.
     * @param eventFactory The event factory.
     */
    public PrettyPrintingWriterWrapper(XMLEventWriter writer, XMLEventFactory eventFactory) {
      this.writer = writer;
      this.eventFactory = eventFactory;
    }

    private String createNewLineAndIndent() {
      return depthCounter == 0 ? "\n"
          : String.format("\n%" + (depthCounter * INDENT_SIZE) + "s", "");
    }

    private void writeEvent(XMLEvent event) throws XMLStreamException {

      // We write a new line and indent for any start element, and for end elements only if inside
      // the element there is more complex content. We test this by verifying that the previous
      // start or end was also an end (of a deeper element) and not this element's start.
      if (event.isStartElement()) {
        writer.add(eventFactory.createSpace(createNewLineAndIndent()));
        depthCounter++;
        lastStartOrEndEvent = event;
      }
      if (event.isEndElement()) {
        depthCounter--;
        if (lastStartOrEndEvent.isEndElement()) {
          writer.add(eventFactory.createSpace(createNewLineAndIndent()));
        }
        lastStartOrEndEvent = event;
      }
      writer.add(event);
    }

    /**
     * Writes all events to the writer. Imposes the right order: first the top level events, then,
     * just before closing the root element, we add in all the nested elements.
     *
     * @param topLevelElement   The top-level element.
     * @param allNestedElements The remaining nested elements.
     * @throws XMLStreamException Unexpected processing errors (typically RDF compliance issues).
     */
    public void write(NestedElement topLevelElement, List<NestedElement> allNestedElements)
        throws XMLStreamException {
      // Write to the output. We write the top level element and its contents and then, just before
      // closing the root element, we add all nested elements in.
      for (XMLEvent event : topLevelElement.getEvents()) {
        if (event.isEndElement() && depthCounter == 1) {
          for (NestedElement nestedElement : allNestedElements) {
            for (XMLEvent nestedEvent : nestedElement.getEvents()) {
              writeEvent(nestedEvent);
            }
          }
        }
        writeEvent(event);
      }
    }
  }
}
