package eu.europeana.metis.common.rdf;

import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.io.StringReader;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Deque;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Optional;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;
import javax.xml.XMLConstants;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLEventFactory;
import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLEventWriter;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.events.Attribute;
import javax.xml.stream.events.Characters;
import javax.xml.stream.events.Namespace;
import javax.xml.stream.events.StartElement;
import javax.xml.stream.events.XMLEvent;

/**
 * <p>This class implements hierarchy normalization on the element hierarchy in RDF+XML content. The
 * problem this functionality aims to solve is that RDF resources (represented by XML elements) can
 * have any kind of nesting, even when generated by Jena (e.g., exported from a model). This
 * functionality solves the issue by 'flattening' the hierarchy in such a way that all resource
 * elements (those with a <code>rdf:about</code> value) are moved to the top of the hierarchy (i.e.,
 * directly underneath the root element, which is assumed to be <code>rdf:RDF</code>). Resource
 * references (<code>rdf:resource</code> attributes) are inserted in the former parent element.
 * Blank nodes (nested anonymous elements without a <code>rdf:about</code> value) will be left
 * untouched. The result will be made "pretty": indented with an indent of 2 spaces.
 * </p>
 * <p>For example, consider the following XML (omitting the namespace declarations):</p>
 * {@snippet lang = "XML":
 * <rdf:RDF>
 *   <Book rdf:about="book_1">
 *     <title>A tale of two cities</title>
 *     <hasAuthor>
 *       <Author rdf:about="author_A">
 *         <name>Charles Dickens</name>
 *       </Author>
 *     </hasAuthor>
 *   </Book>
 * </rdf:RDF>
 *}
 * <p>Hierarchy normalization will transform this data into the following equivalent structure:</p>
 * {@snippet lang = "XML":
 * <rdf:RDF>
 *   <Book rdf:about="book_1">
 *     <title>A tale of two cities</title>
 *     <hasAuthor rdf:resource="author_A"></hasAuthor>
 *   </Book>
 *   <Author rdf:about="author_A">
 *     <name>Charles Dickens</name>
 *   </Author>
 * </rdf:RDF>
 *}
 * <p>Note that we have extracted the nested object (<code>Author</code>) from the containing one
 * (<code>Book</code> and moved it up to the root level. In order to preserve the relation, we
 * instead added a <code>rdf:resource</code> reference where the nested object was.
 * </p>
 * <p>The benefit of hierarchy normalization lies in normalizing the otherwise unpredictable
 * structure of XML data. This is useful, for instance, ahead of applying an XSLT: the XSLT can now
 * be made to assume the flattened structure and hence be simpler.
 * </p>
 * <p> This implementation of hierarchy normalization is not streamed, as we need to keep
 * significant portions of the content in memory (namely, all nested elements, so that we can add
 * them in later at the right place). This means that this implementation is designed to work with
 * small amounts of data (like individual records and contextual items). A logical alternative would
 * have been to load in Jena and then write some custom export tool. This seems to be more complex
 * than the approach implemented here (even though it could perhaps have been made more performant).
 * </p>
 * <p> <b>Please note:</b> <i>The input data is assumed to be valid RDF+XML.</i> This means that
 * this functionality does not always check RDF+XML compliance, but rather acts 'in good faith'.
 * In some cases, particularly where changes are made, we do check rudimentary compliance. For
 * example, if a property has multiple child resources in the input data (not allowed in RDF+XML),
 * an exception may be thrown as the property cannot have multiple <code>rdf:resource</code>
 * attributes after hierarchy normalization. But it is important to note that no guarantee exists
 * that an exception will be thrown if the record is RDF+XML non-compliant.
 * </p>
 * <p> <b>Exception to the expectation of RDF+XML compliance:</b> At the time of writing, some
 * provenance information is encoded in a manner that is not compliant with RDF+XML. Specifically,
 * attributes <code>edm:wasGeneratedBy</code> and <code>edm:confidenceLevel</code> are accepted on
 * properties. As this does not affect the structure of the data, hierarchy normalization as
 * implemented here will accept and preserve these annotations.
 * </p>
 */
public final class RdfXmlHierarchyNormalization {

  // TODO also do namespace sorting and cleanup some way (less urgent)? If we extract and move a
  //  whole section some namespace declarations may no longer be needed. Or they may be duplicate
  //  (already defined identically further up in the hierarchy). This is not a correctness issue,
  //  but it would be cleaner if they were to be removed.
  //  Another solution is to move all namespaces to the top. Collect them all, assign prefixes
  //  to them, put them in the root element and emit all following statements with adjusted prefixes.
  // TODO We could perhaps stream it better by writing each section as we complete it. Then
  //  we don't keep so much in memory (assuming there are not so many levels of nesting and that
  //  sections are relatively small and that the top-level section does not contain so much own
  //  content). The problem is that this may not work with the namespace improvements as suggested
  //  above.

  private static final String RDF_NAMESPACE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
  private static final String RDF_ABOUT = "about";
  private static final String RDF_RESOURCE = "resource";

  private RdfXmlHierarchyNormalization() {
  }

  /**
   * Perform hierarchy normalization on the provided content.
   *
   * @param content The content to normalize.
   * @return The normalized content.
   * @throws ComplianceException When non-compliance is detected.
   */
  public static String normalizeHierarchy(String content) throws ComplianceException {
    final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    normalizeHierarchy(content, outputStream);
    return outputStream.toString();
  }

  /**
   * Perform hierarchy normalization on the provided content.
   *
   * @param content The content to normalize.
   * @param result  The stream where the result is to be written. Content will be written in the
   *                default character encoding.
   * @throws ComplianceException When non-compliance is detected.
   */
  public static void normalizeHierarchy(String content, OutputStream result)
      throws ComplianceException {
    try {
      normalizeHierarchyInternal(content, result);
    } catch (XMLStreamException e) {
      throw new XmlComplianceException("XML Noncompliance detected. " + e.getMessage(), e);
    }
  }

  /**
   * Perform hierarchy normalization on the provided content.
   *
   * @param content The content to normalize.
   * @param result  The stream where the result is to be written. Content will be written in the
   *                default character encoding.
   * @throws XMLStreamException     When XML non-compliance is detected.
   * @throws RdfComplianceException When RDF non-compliance is detected.
   */
  private static void normalizeHierarchyInternal(String content, OutputStream result)
      throws XMLStreamException, RdfComplianceException {

    // Set up the input with the XML data as provided.
    final XMLEventFactory eventFactory = XMLEventFactory.newInstance();
    final XMLInputFactory factory = XMLInputFactory.newInstance();
    factory.setProperty(XMLConstants.ACCESS_EXTERNAL_DTD, "");
    factory.setProperty(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
    final XMLEventReader reader = factory.createXMLEventReader(new StringReader(content));

    // Create and bootstrap the nested section (scope) stack (that includes the top-level section)
    // and the list of sections (that excludes the top-level section). Note: we will add new
    // nested sections to the list upon creation: this creates a breadth-first list (if we were to
    // add it upon completion, we would get a depth-first list instead).
    final NestedSection topLevelSection = new NestedSection(true, Collections.emptyMap());
    final Deque<NestedSection> sectionStack = new ArrayDeque<>();
    sectionStack.add(topLevelSection);
    final List<NestedSection> allNestedSections = new ArrayList<>();

    // Read all events and separate them by section, preserving the order within each nested section.
    while (reader.hasNext()) {
      final XMLEvent currentEvent = reader.nextEvent();

      // Start writing a new nested section if we find an element with an ID (i.e., rdf:about
      // value). We make an exception for the root element (i.e., rdf:RDF) as we should never
      // create a nested section for it or its children (they are already in the right place).
      // We must also add a new reference to the parent element.
      final boolean isNotAtRootElementBeforeEvent = sectionStack.size() > 1 ||
          sectionStack.getLast().getCurrentDepth() > 1;
      if (isNotAtRootElementBeforeEvent && currentEvent.isStartElement()) {
        final StartElement element = currentEvent.asStartElement();
        final String elementId = Optional.ofNullable(element.getAttributeByName(
                new QName(RDF_NAMESPACE, RDF_ABOUT)))
            .map(Attribute::getValue).filter(id -> !id.isBlank()).orElse(null);
        if (elementId != null) {
          setReferenceForCurrentElement(elementId, sectionStack.getLast(), eventFactory);
          final NestedSection nestedSection = new NestedSection(false,
              sectionStack.getLast().getCurrentAdditionalNamespaces());
          sectionStack.addLast(nestedSection);
          allNestedSections.add(nestedSection);
        }
      }

      // Add the element and maintain the counter and namespace stack.
      addEventToSection(currentEvent, sectionStack.getLast(), eventFactory);

      // Finalize the nested element if we have just ended its root element. All we need to
      // do is pop it from the stack, then we're back in the parent where we left off, we continue
      // writing there. Of course, we only do this if we are not already in the top-level section.
      if (currentEvent.isEndElement() && sectionStack.getLast().getCurrentDepth() == 0
          && sectionStack.size() > 1) {
        sectionStack.removeLast();
      }
    }

    // Write the output for the normalized XML data.
    final XMLEventWriter writer = XMLOutputFactory.newInstance().createXMLEventWriter(result);
    new PrettyPrintingWriterWrapper(writer, eventFactory).write(topLevelSection, allNestedSections);
  }

  /**
   * Adds an event to the section. This method is used while we are receiving events, and we
   * determine it should be part of this section. We update other properties of this section based
   * on the event that is received.
   *
   * @param event        The event to add.
   * @param section      The section to add the event to.
   * @param eventFactory The event factory for creating event-related objects.
   */
  private static void addEventToSection(XMLEvent event, NestedSection section,
      XMLEventFactory eventFactory) {

    // Add the event. Characters go into the buffer. If we find a non-character event, we
    // decide on whether to add all the characters to the event list, or discard (purge) them.
    // We only add the characters if we are between a start and an end, and the start does not
    // have a rdf:resource link. So between start and start, between end and end, and between
    // end and start, we don't add characters.
    if (event.isCharacters()) {
      section.characterBuffer.add(event.asCharacters());
    } else {
      final boolean isBetweenNonReferenceStartAndEnd = !section.events.isEmpty() &&
          section.events.getLast().isStartElement() && event.isEndElement() &&
          section.events.getLast().asStartElement().getAttributeByName(
              new QName(RDF_NAMESPACE, RDF_RESOURCE)) == null;
      if (isBetweenNonReferenceStartAndEnd) {
        section.events.addAll(section.characterBuffer);
      }
      section.characterBuffer.clear();
      section.events.add(event);
    }

    // Update the namespace stack (and implicitly the depth). This must be after deciding on
    // purging characters, so that the depth still reflects the depth of the characters for which
    // we are making this decision.
    if (event.isStartElement()) {

      // Add a namespace list to the stack.
      final List<Namespace> namespaces = new ArrayList<>();
      section.namespaceStack.addLast(namespaces);

      // We only add the actual namespaces if this new element is not the root element.
      if (section.isNotAtRootElement()) {
        event.asStartElement().getNamespaces().forEachRemaining(namespaces::add);
      }
    }
    if (event.isEndElement()) {

      // Purge this depth's namespace list from the stack.
      section.namespaceStack.removeLast();
    }

    // If this is the first event of this section, then it is this section's root element, and it
    // needs to be equipped with all the namespaces it inherits from its ancestor. Otherwise,
    // these would be lost as soon as this element is inserted at the root level. We do this after
    // the namespace stack is updated for this element, so that we also get the namespaces that
    // this element itself declares.
    // Note: in reality there are always inherited namespaces (if we are not in the root element)
    // because we add the rdf:resource value to the parent element before we create a new section.
    // So there will always be the rdf namespace. So there is no point optimizing by checking
    // whether there even are inherited namespaces.
    if (section.isNotAtRootElement() && section.events.size() == 1) {
      final StartElement startElement = section.events.getFirst().asStartElement();
      section.events.set(0, eventFactory.createStartElement(
          startElement.getName().getPrefix(), startElement.getName().getNamespaceURI(),
          startElement.getName().getLocalPart(), startElement.getAttributes(),
          section.getCurrentAdditionalNamespaces().values().iterator(),
          startElement.getNamespaceContext()));
    }
  }

  /**
   * This method is called as we are receiving events, and we determine that we need to start a
   * new (nested) section. We register the new section (by its <code>rdf:about</code>) with this
   * section: a <code>rdf:resource</code> reference needs to be added to the current element to
   * refer to it.
   *
   * @param reference    The reference to register.
   * @param section      The section where to set the reference.
   * @param eventFactory The event factory for creating event-related objects.
   * @throws RdfComplianceException When RDF non-compliance is detected.
   */
  private static void setReferenceForCurrentElement(String reference, NestedSection section,
      XMLEventFactory eventFactory) throws RdfComplianceException {

    // The last added non-character element at this point must be a start element (i.e., be the
    // parent element), otherwise it is a sibling, which is not allowed. Also, if there already
    // is a reference, it is proof of a virtual sibling.
    final boolean isStartElementWithExistingReference = Optional.of(section.events.getLast())
        .filter(XMLEvent::isStartElement).map(XMLEvent::asStartElement)
        .map(element -> element.getAttributeByName(new QName(RDF_NAMESPACE, RDF_RESOURCE)))
        .isPresent();
    if (!section.events.getLast().isStartElement() || isStartElementWithExistingReference) {
      throw new RdfComplianceException("Could not add reference " + reference
          + ": RDF property contains more than one object.");
    }
    final StartElement currentElement = section.events.getLast().asStartElement();

    // Find the RDF namespace. First see if the namespace is already declared (which will almost
    // certainly be the case in the context as the root is rdf:ABOUT).
    // Note: it is possible for a namespace to be declared in the additional namespaces but not in
    // the namespace context. This is because it may have been added earlier during processing
    // (i.e., in a parent element when a parent section was extracted).
    // Note that we don't accept default namespaces: attributes don't work with them.
    String rdfPrefix = currentElement.getNamespaceContext().getPrefix(RDF_NAMESPACE);
    if (rdfPrefix == null || XMLConstants.DEFAULT_NS_PREFIX.equals(rdfPrefix)) {
      rdfPrefix = section.getCurrentAdditionalNamespaces().entrySet().stream()
          .filter(entry -> entry.getValue().getNamespaceURI().equals(RDF_NAMESPACE))
          .map(Entry::getKey).findAny().orElse(null);
    }

    // If the namespace was not already declared, it must have been unset and then set again in
    // this node's child (where a rdf:about is present). In this very unlikely edge case, we will
    // create a new namespace to be added to the node. We need to find a non-existing prefix.
    // Note: even though it is possible for a prefix to be declared in the additional namespaces
    // but not in the namespace context (it may have been added earlier during processing), this
    // will only happen for this namespace, and would therefore have been detected above. But we
    // check just to be sure.
    // Note that we don't accept default namespaces: attributes don't work with them.
    final boolean newNamespaceNeeded = rdfPrefix == null
        || XMLConstants.DEFAULT_NS_PREFIX.equals(rdfPrefix);
    if (newNamespaceNeeded) {
      final Map<String, Namespace> additionalNamespaces = section.getCurrentAdditionalNamespaces();
      for (int i = 0; ; i++) {
        final String candidatePrefix = "rdf" + i;
        if (currentElement.getNamespaceContext().getNamespaceURI(candidatePrefix) == null &&
            !additionalNamespaces.containsKey(candidatePrefix)) {
          rdfPrefix = candidatePrefix;
          break;
        }
      }
    }

    // If a new namespace is needed, create it, add it to the element and also to the stack.
    final Iterator<Namespace> newNamespaces;
    if (newNamespaceNeeded) {
      final Namespace newNamespace = eventFactory.createNamespace(rdfPrefix, RDF_NAMESPACE);
      section.namespaceStack.getLast().add(newNamespace);
      final Iterable<Namespace> currentNamespaces = currentElement::getNamespaces;
      newNamespaces = Stream.concat(Stream.of(newNamespace),
          StreamSupport.stream(currentNamespaces.spliterator(), false)).iterator();
    } else {
      newNamespaces = currentElement.getNamespaces();
    }

    // Create the new attribute and add it to the list.
    final Iterable<Attribute> currentAttributes = currentElement::getAttributes;
    final Attribute newAttribute = eventFactory.createAttribute(
        new QName(RDF_NAMESPACE, RDF_RESOURCE, rdfPrefix), reference);
    final Iterator<Attribute> newAttributes = Stream.concat(Stream.of(newAttribute),
        StreamSupport.stream(currentAttributes.spliterator(), false)).iterator();

    // Apply the changes to the current event.
    section.events.set(section.events.size() - 1, eventFactory.createStartElement(
        currentElement.getName().getPrefix(), currentElement.getName().getNamespaceURI(),
        currentElement.getName().getLocalPart(), newAttributes, newNamespaces,
        currentElement.getNamespaceContext()));
  }

  /**
   * <p>This represents a section of content in the hierarchy. This is either the top level section
   * (i.e., the document, the <code>rdf:RDF</code> and its immediate children), or it represents a
   * nested section defined by an element with <code>rdf:about</code> value and all its content.
   * </p>
   * <p>As content is added to this section, all spacing/indenting is purged from the content.
   * </p>
   * <p>This object represents precisely the units of data that need to be moved around. Thus, an
   * instance of this class exists for an element in the data if and only if:
   * <ul>
   *   <li>The element is the root element, or</li>
   *   <li>The element has a <code>rdf:about</code> value and is not a direct child of the root
   *   element.</li>
   * </ul>
   * All parts of the data are in precisely one instance of this class (that of their closest
   * ancestor that meets either of these criteria). Furthermore, all instances of this class
   * (except the top-level section) represent a section of data to be moved to another position so
   * that it becomes a direct child of the root element.
   * </p>
   */
  private static class NestedSection {

    /**
     * The events in this section. the last event in this list is always a non-character event.
     */
    private final List<XMLEvent> events = new ArrayList<>();

    /**
     * Character events are buffered here until they can all be written together with the next
     * non-character event (or purged, depending on the situation).
     */
    private final List<Characters> characterBuffer = new ArrayList<>();

    /**
     * List of inherited namespaces (declared in all parent elements of this section). These
     * namespaces will all need to be declared specifically if we move this nested section to be a
     * child of the root element. Namespaces that are declared in the root element are therefore
     * not included. Note: a default namespace declaration has prefix <code>""</code> (the empty
     * string - see {@link javax.xml.XMLConstants#DEFAULT_NS_PREFIX}). This prefix cannot occur
     * otherwise. As a consequence, the map by prefix will also work naturally for default
     * namespace declarations. Note that default namespaces don't apply to attributes, just to
     * element names.
     */
    private final Map<String, Namespace> inheritedNamespaces;

    /**
     * This keeps track of namespaces added for each level in this section (except the root
     * element). The current depth will always be equal to the size of this stack.
     */
    private final Deque<List<Namespace>> namespaceStack = new ArrayDeque<>();

    /**
     * Indicates whether this is the top-level section in the data (containing the root element).
     */
    private final boolean isTopLevelSection;

    /**
     * Constructor.
     *
     * @param isTopLevelSection   Whether this is the top-level section.
     * @param inheritedNamespaces List of inherited namespaces declared in all parent elements
     *                            (that need to be declared specifically if we move this nested
     *                            section to be a child of the root element).
     */
    public NestedSection(boolean isTopLevelSection, Map<String, Namespace> inheritedNamespaces) {
      this.isTopLevelSection = isTopLevelSection;
      this.inheritedNamespaces = new HashMap<>(inheritedNamespaces);
    }

    /**
     * The current depth is always equal to the size of the namespace stack.
     * @return The current depth.
     */
    public int getCurrentDepth() {
      return namespaceStack.size();
    }

    /**
     * We are at the root element (i.e., <code>rdf:RDF</code>) if and only if this is the top level
     * section and, within this section, we are not deeper than depth 1 (i.e., inside
     * <code>rdf:RDF</code> but not inside any of its child elements).
     *
     * @return True if and only if we are not at the root element.
     */
    private boolean isNotAtRootElement() {
      return !this.isTopLevelSection || getCurrentDepth() > 1;
    }

    /**
     * Compile the additional namespaces that were added in anything other than the root element.
     * This is done by taking the inherited namespaces that this nested section came with, and
     * adding (or replacing) any new declarations that were found within this nested section. We
     * need to ensure that if a new namespace is declared for a prefix, the newest (i.e., the
     * 'deepest' in the hierarchy) declaration wins.
     *
     * @return The additional namespaces at the current point in the event list, in a map with the
     * prefix as key.
     */
    public Map<String, Namespace> getCurrentAdditionalNamespaces() {
      final Map<String, Namespace> result = new HashMap<>(inheritedNamespaces);
      namespaceStack.stream().flatMap(Collection::stream)
          .forEach(namespace -> result.put(namespace.getPrefix(), namespace));
      return Collections.unmodifiableMap(result);
    }
  }

  /**
   * This is a wrapper around an event writer that adds indentation based on the current depth.
   */
  private static class PrettyPrintingWriterWrapper {

    /** The indent size (number of spaces). **/
    private static final int INDENT_SIZE = 2;

    /** The wrapped writer. **/
    private final XMLEventWriter writer;

    /** The factory for creating (indent) events. **/
    private final XMLEventFactory eventFactory;

    /** The current depth while writing. **/
    private int depthCounter = 0;

    /** The last event that was a start or an end: is used to determine whether to indent. **/
    private XMLEvent lastStartOrEndEvent = null;

    /**
     * Constructor.
     *
     * @param writer       The wrapped writer.
     * @param eventFactory The event factory.
     */
    public PrettyPrintingWriterWrapper(XMLEventWriter writer, XMLEventFactory eventFactory) {
      this.writer = writer;
      this.eventFactory = eventFactory;
    }

    private String createNewLineAndIndent() {
      return "\n" + " ".repeat(depthCounter * INDENT_SIZE);
    }

    private void writeEvent(XMLEvent event) throws XMLStreamException {

      // We write a new line and indent for any start element, and for end elements only if inside
      // the element there is more complex content. We test this by verifying that the previous
      // start or end was also an end (of a deeper element) and not this element's start.
      if (event.isStartElement()) {
        writer.add(eventFactory.createSpace(createNewLineAndIndent()));
        depthCounter++;
        lastStartOrEndEvent = event;
      }
      if (event.isEndElement()) {
        depthCounter--;
        if (lastStartOrEndEvent.isEndElement()) {
          writer.add(eventFactory.createSpace(createNewLineAndIndent()));
        }
        lastStartOrEndEvent = event;
      }
      writer.add(event);
    }

    /**
     * Writes all events to the writer. Imposes the right order: first the top level events, then,
     * just before closing the root element, we add in all the nested sections.
     *
     * @param topLevelSection   The top-level section.
     * @param allNestedSections The remaining nested sections.
     * @throws XMLStreamException Unexpected processing errors (typically RDF compliance issues).
     */
    public void write(NestedSection topLevelSection, List<NestedSection> allNestedSections)
        throws XMLStreamException {

      // Write to the output. We write the top level section and its contents and then, just before
      // closing the root element, we add all nested sections in.
      for (XMLEvent event : topLevelSection.events) {
        if (event.isEndElement() && depthCounter == 1) {
          for (NestedSection nestedSection : allNestedSections) {
            write(nestedSection, Collections.emptyList());
          }
        }
        writeEvent(event);
      }
    }
  }
}
